package com.learn.material3testing.ui.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3C5BA9)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFDAE1FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001849)
val md_theme_light_secondary = Color(0xFF006688)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC2E8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2C)
val md_theme_light_tertiary = Color(0xFF3F6919)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFBEF291)
val md_theme_light_onTertiaryContainer = Color(0xFF0C2000)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_outline = Color(0xFF6F797A)
val md_theme_light_background = Color(0xFFFAFDFC)
val md_theme_light_onBackground = Color(0xFF191C1C)
val md_theme_light_surface = Color(0xFFF7FAF9)
val md_theme_light_onSurface = Color(0xFF191C1C)
val md_theme_light_surfaceVariant = Color(0xFFDBE4E6)
val md_theme_light_onSurfaceVariant = Color(0xFF3F484A)
val md_theme_light_inverseSurface = Color(0xFF2D3131)
val md_theme_light_inverseOnSurface = Color(0xFFEFF1F0)
val md_theme_light_inversePrimary = Color(0xFFB3C5FF)
val md_theme_light_surfaceTint = Color(0xFF3C5BA9)
val md_theme_light_outlineVariant = Color(0xFFBFC8CA)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFB3C5FF)
val md_theme_dark_onPrimary = Color(0xFF002B74)
val md_theme_dark_primaryContainer = Color(0xFF20428F)
val md_theme_dark_onPrimaryContainer = Color(0xFFDAE1FF)
val md_theme_dark_secondary = Color(0xFF77D1FF)
val md_theme_dark_onSecondary = Color(0xFF003549)
val md_theme_dark_secondaryContainer = Color(0xFF004D68)
val md_theme_dark_onSecondaryContainer = Color(0xFFC2E8FF)
val md_theme_dark_tertiary = Color(0xFFA3D578)
val md_theme_dark_onTertiary = Color(0xFF1A3700)
val md_theme_dark_tertiaryContainer = Color(0xFF285000)
val md_theme_dark_onTertiaryContainer = Color(0xFFBEF291)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_outline = Color(0xFF899294)
val md_theme_dark_background = Color(0xFF252929)
val md_theme_dark_onBackground = Color(0xFFE0E3E2)
val md_theme_dark_surface = Color(0xFF101414)
val md_theme_dark_onSurface = Color(0xFFC4C7C6)
val md_theme_dark_surfaceVariant = Color(0xFF3F484A)
val md_theme_dark_onSurfaceVariant = Color(0xFFBFC8CA)
val md_theme_dark_inverseSurface = Color(0xFFE0E3E2)
val md_theme_dark_inverseOnSurface = Color(0xFF191C1C)
val md_theme_dark_inversePrimary = Color(0xFF3C5BA9)
val md_theme_dark_surfaceTint = Color(0xFFB3C5FF)
val md_theme_dark_outlineVariant = Color(0xFF3F484A)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF102452)
